DROP TABLE IF EXISTS users_roles;
DROP TABLE IF EXISTS images;
DROP TABLE IF EXISTS career_request;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS roles;
